# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1cb0f7cf9607d6d11a9224ff6a624ed4204d1fc2e0fd42b62bb3b2a42049e6de7de55c9700e41f2059dd4c166f17cec639ceabe416ed95fdbafb98e5cd5bc2d3

test:
  secret_key_base: 7e9e46421cb4bbb274f82cabd24742ecf0dfdc69a013b0df412e4e0fa4f51d55101b217fea29dd4e36e7e3bacc547125a91231ba58dc70044e94f6b3b6940ff6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
